import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ThemeProvider>
        <body className="min-h-full flex flex-col gap-4 p-4">
          <nav className="flex flex-wrap items-center justify-center gap-3 rounded-2xl p-4 shadow-md backdrop-blur-md">
            <Link
              href="/"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-emerald-600 hover:bg-emerald-600 hover:text-white"
            >
              Home
            </Link>

            <Link
              href="/rendering/static"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-blue-600 hover:bg-blue-600 hover:text-white"
            >
              Static Rendering
            </Link>

            <Link
              href="/rendering/dynamic"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-purple-600 hover:bg-purple-600 hover:text-white"
            >
              Dynamic Rendering
            </Link>

            <Link
              href="/products"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-yellow-600 hover:bg-yellow-600 hover:text-white"
            >
              Products (params)
            </Link>

            <Link
              href="/slider"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-cyan-600 hover:bg-cyan-600 hover:text-white"
            >
              Image Slider
            </Link>

            <Link
              href="/get"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-green-600 hover:bg-green-600 hover:text-white"
            >
              GET Route Handler
            </Link>

            <Link
              href="/profile"
              className="rounded-xl border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 transition-all duration-300 hover:-translate-y-0.5 hover:border-pink-600 hover:bg-pink-600 hover:text-white"
            >
              Profile Route Handler
            </Link>
          </nav>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
